### ISSUE TITLE
minDate

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#1]
I set minDate as below:
```javascript
smartfaceCalendar.minDate = new Date("13 October, 2015");
```
It doesn't work, I can select date before than this new min date value.

**Comment by olcayertas** [comment]
Please use ISO date formatted string for dates.
All dates stored as string.

**Comment by smfMerve** [comment]
I tried to set minDate as below:

var myMinDate = new Date('05 October 2015 14:48 UTC');
smartfaceCalendar.setMinDate(myMinDate.toISOString());

When I try to get mindate value, I get the right value(the one I set - 5october).
But I can make selections before than 5 october 2015.

**Comment by olcayertas** [comment]
Fixed in new version.
User can set date as string (with format) or as long value.
Dates before minimum date or after maximum dates will be showed as disabled.
User can not select or long press on disabled dates.
```javascript
var minDate = new Date();
minDate.setDate(1);

var maxDate = new Date();
maxDate.setDate(31);

//use long
smartfaceCalendar.setMinDate(minDate.getTime());
smartfaceCalendar.setMaxDate(maxDate.getTime());

// or you can use string with format

smartfaceCalendar.setMinDate(minDate.toISOString(), "YYYY-MM-DDTHH:mm:ss.sssZ");
smartfaceCalendar.setMaxDate(maxDate.toISOString(), "YYYY-MM-DDTHH:mm:ss.sssZ");
```

**Comment by olcayertas** [comment]
@mrvbicakci it is fixed.
