### ISSUE TITLE
setSwipeEnabled

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#11]
I can't run  `smartfaceCalendar.setSwipeEnabled(false);`
It gives the error in the screenshot:

![screenshot_20160201-180819](https://cloud.githubusercontent.com/assets/12133528/12722810/536fed12-c90f-11e5-82c1-459c62ba0a6d.png)

**Comment by olcayertas** [comment]
Fixed
