### ISSUE TITLE
next and previous images

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#14]
Still, images do not change:
````Javascript
smartfaceCalendar.setNextImage("myiconsmall.png");
smartfaceCalendar.setPreviousImage("myiconsmall.png");
````

**Comment by olcayertas** [comment]
I have tested it without file extension and it is working. Try without file extension.

**Comment by olcayertas** [comment]
I have tried it with file extension and it is working.

**Comment by mrvbicakci** [comment]
I tried without extension, still I can't change icons. I'm trying to chnage them on a buttons onPressed event.

**Comment by olcayertas** [comment]
Fixed

**Comment by mrvbicakci** [comment]
I used the code below:

```
smartfaceCalendar.setNextImage("logo");
smartfaceCalendar.setPreviousImage("logo");
```

This code above doesn't change icons itself. 
After that when I try to change setSwipeEnabled property to true or false, then icons change.

**Comment by olcayertas** [comment]
Fixed
