### ISSUE TITLE
setSwipeEnabled methods triggers setOnMonthChanged event

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#15]
Each time I use setSwipeEnabled, it triggers setOnMonthChanged event.

**Comment by olcayertas** [comment]
Fixed

**Comment by mrvbicakci** [comment]
This problem continues with the latest plugin.
If I change setSwipeEnabled, each time it triggers setOnMonthChanged event.

**Comment by olcayertas** [comment]
Fixed
