### ISSUE TITLE
top, left, height and width properties

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#2]
I tried to set these values as below:

```javascript
smartfaceCalendar.top = 500
smartfaceCalendar.left = 0;
smartfaceCalendar.height = 600;
smartfaceCalendar.width = 600;
```

I couldn't change values.

**Comment by smfMerve** [comment]
top and left works fine when used with setter: setTop(); and setLeft();

But setWidth(400); and setHeight(800); gives undefined error.
(undeifned is not a function - evaluating smartfaceCalendar.setWidth(400))

**Comment by olcayertas** [comment]
We have decided to use setter and getters.
Users won't be able to access fields publicly.
Setters will apply the changes.

**Comment by olcayertas** [comment]
Fixed.
