### ISSUE TITLE
goToday triggers setOnMonthChanged gets triggered 2 times

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#20]
I changed month to March.
The called goToday method. It triggers setOnMonthChanged for 2 times.

```
smartfaceCalendar.setOnMonthChanged(function (e) {
	alert("Month changed : " + e.oldMonth + " → " +  + e.newMonth);
});
```

It shows me two alerts:
1st one is: "Month changed: 3 -> 2"
2nd one is "Month changed: 3 -> 3"

**Comment by olcayertas** [comment]
It is intended behaviour. User should handle it.

**Comment by olcayertas** [comment]
It is intended behaviour. User should handle it.
