### ISSUE TITLE
I can't use Calendar as class name

### ISSUE THREAD

**Issue by muzeyyenn** [SmartfaceIO/plugin-calendar-android#23]
When i use Calendar as class name of my plugin it doesn't apper and it doesn't give error. I guess it is creating Java Calendar object instead of my plugin. I have revert my plugin name to SmartfaceCalendar and it is working.
```
var calendar = new Calendar("activity"); //Not working
var calendar = new SmartfaceCalendar("activity") //Working
```

Plugin project: 
Z:\13.Personal Folders\merve.bicakci\bugs\6673

**Comment by Mobinexbiz** [comment]
Calendar name can't be used as it conflicts with Java's Calendar. We will use SmartfaceCalendar until name conflict resolved.

**Comment by olcayertas** [comment]
Calendar name can't be used as it conflicts with Java's Calendar. We will use SmartfaceCalendar until name conflict resolved.
