### ISSUE TITLE
touchEnabled property

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#3]
I set `touchEnabled` as false:
```javascript
smartfaceCalendar.touchEnabled = false;
```
But I can still trigger `onTouch` and `onTouchEnd` events.

**Comment by smfMerve** [comment]
also, I tried to use it as below:
smartfaceCalendar.setTouchEnabled(false); 

nothing changed, I can trigger touch events

**Comment by olcayertas** [comment]
Fixed
