### ISSUE TITLE
swipeEnabled

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#4]
I set `swipeEnabled` as `false` but I can still use swipe.
```javascript
smartfaceCalendar.swipeEnabled = false;
```

**Comment by smfMerve** [comment]
Also I tried it as below:
smartfaceCalendar.setSwipeEnabled(false);

Still I can swipe.

**Comment by olcayertas** [comment]
Fixed

**Comment by mrvbicakci** [comment]
I can't run smartfaceCalendar.setSwipeEnabled(false);
It gives the error in the screenshot:

![screenshot_20160201-180819](https://cloud.githubusercontent.com/assets/12133528/12722741/efb8d612-c90e-11e5-9558-f9a953855737.png)
