### ISSUE TITLE
top and left values change to default values after swipe is used

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/plugin-calendar-android#5]
When pressed to a button, I chnaged top and left values as below:
```javascript
smartfaceCalendar.setTop(600);
smartfaceCalendar.setLeft(0);
```
Then, I tried to change month by swipe or by pressing next and previous icons. Calendar takes the default top and left values.
![top-left](https://cloud.githubusercontent.com/assets/12133528/12553512/a3efd908-c380-11e5-890d-b051398b7f35.png)

**Comment by olcayertas** [comment]
Fixed.
